all:
  hosts:
    control-plane:
      ansible_host: 18.188.50.77
      ip: 10.0.5.201
      access_ip: 10.0.5.201
    worker1:
      ansible_host: 3.148.186.176
      ip: 10.0.5.58
      access_ip: 10.0.5.58
    worker2:
      ansible_host: 3.142.122.67
      ip: 10.0.6.143
      access_ip: 10.0.6.143
    worker3:
      ansible_host: 18.217.179.119
      ip: 10.0.6.174
      access_ip: 10.0.6.174
  children:
    kube_control_plane:
      hosts:
        control-plane:
    kube_node:
      hosts:
        control-plane:
        worker1:
        worker2:
        worker3:
    etcd:
      hosts:
        control-plane:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/salon-key.pem
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3
